# Use Node.js LTS version
FROM node:18-alpine

# Install git and nodemon
RUN apk add --no-cache git curl \
    && npm install -g nodemon

# Set working directory
WORKDIR /app

COPY lost_in_laff .

WORKDIR /app/lost_in_laff

RUN rm -rf .next node_modules

EXPOSE 3000

RUN npm install 
# RUN npm run build

CMD ["npm", "run", "dev"]