version: '3'

networks:
  local_network:
    driver: bridge

services:
  lost_in_lafferre:
    build:
      context: .
      args:
        MODE: ${MODE:-local}  # Uses an environment variable, defaults to 'local' if not set
        BRANCH: ${BRANCH:-dev}  # Uses an environment variable, defaults to 'main' if not set
    container_name: capstone 
    networks:
      - local_network
    ports:
      - "3000:3000"
    restart: unless-stopped 
    # profiles:
    #   - remote

  # lost_in_lafferre_local:
  #   build:
  #     context: .
  #     args:
  #       MODE: local 
  #       BRANCH: dev
  #   container_name: cap_local 
  #   ports:
  #     - "3000:3000"
  #   restart: no
  #   profiles:
  #     - local
