version: '3'

networks:
  local_network:
    driver: bridge

services:
  lost_in_lafferre_remote:
    build:
      context: .
      args:
        MODE: remote
    container_name: cap_remote 
    networks:
      - local_network
    ports:
      - "3000:3000"
    restart: always
    profiles:
      - remote

  lost_in_lafferre_local:
    build:
      context: .
      args:
        MODE: remote
    container_name: cap_local 
    ports:
      - "3000:3000"
    restart: no
    profiles:
      - local